source :rubygems

gem 'sinatra', '1.3.2'
gem 'service_manager', '0.6.4'
gem 'activerecord', '3.1.3'
gem 'sqlite3', '1.3.5'

group :development do
  gem 'rspec', '2.11.0'
  gem 'cucumber', '1.2.1'
  gem 'capybara', '2.0.0.beta2'
  gem 'launchy', '2.1.0'
  gem 'database_cleaner', '0.7.0'
end

