# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c641a14db5d3a064e1edb906801a45d4f28a7fc0dbadab403d4fd285dc5c829b040bdbfb678be886532d46ba669fe9f72e2d1180c34a6fd555a1a3b0301f5340

test:
  secret_key_base: b2f8cc7e8a62597d39662f5d0d60df8cb813e0e36d83ec0900a070e59eb28501679e6992e38442a78b441b632f15e37f1fd7ab1fd311aa88dccc17d2517b5eb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
